baseURL = "https://decadentserpent.com/"
languageCode = "en-gb"
title = "Decadent Serpent"
theme = "serpent"
paginate = 12
enableRobotsTXT = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "The One Place for All Things Culture"
  donateURL = "https://buymeacoffee.com/decadentserpent"
  instagramURL = "https://www.instagram.com/decadentserpent"
  twitterURL = "https://www.x.com/decadentserpent"
  googleAnalyticsID = "G-7JG1T5WZ60"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[markup.tableOfContents]
  startLevel = 2
  endLevel = 3

[related]
  includeNewer = true
  threshold = 80
  toLower = true
  [[related.indices]]
    name = "categories"
    weight = 100
  [[related.indices]]
    name = "tags"
    weight = 80
  [[related.indices]]
    name = "author"
    weight = 40

[sitemap]
  changefreq = "weekly"
  priority = 0.5
